# new list of online Web Service sources
sources=[]

# append online Web Service sources
# QGIS_WMS.xml
sources.append(["connections-wms", "EUROPE_COPERNICUS", "", "", "","http://servicios.idee.es/wms/copernicus-landservice-spain?", "", "", ""])
sources.append(["connections-wms", "EUROPE_ESPAGNE_IGN_MAPAS_ANTIGUOS_DE_MADRID", "", "", "","http://www.ign.es/wms/planos?", "", "", ""])
sources.append(["connections-wms", "EUROPE_ESPAGNE_IGN_MINUTAS_CARTOGRAPHICAS", "", "", "","http://www.ign.es/wms/minutas-cartograficas?", "", "", ""])
sources.append(["connections-wms", "EUROPE_ESPAGNE_IGN_ORTOFOTOS", "", "", "","http://www.ign.es/wms-inspire/pnoa-ma?", "", "", ""])
sources.append(["connections-wms", "EUROPE_ESPAGNE_IGN_ORTOFOTOS_HISTORICAS", "", "", "","http://www.ign.es/wms/pnoa-historico?", "", "", ""])
sources.append(["connections-wms", "EUROPE_ESPAGNE_IGN_PRIMERA_EDICION_MTN50", "", "", "","http://www.ign.es/wms/primera-edicion-mtn?", "", "", ""])
sources.append(["connections-wms", "FRANCE_BRGM_ADES", "", "", "","http://services.ades.eaufrance.fr/carto/wms", "", "", ""])
sources.append(["connections-wms", "FRANCE_BRGM_GEOLOGIE_HYDROGEOLOGIE_GRAVIMETRIE", "", "", "","http://geoservices.brgm.fr/geologie", "", "", ""])
sources.append(["connections-wms", "FRANCE_BRGM_OBSERVATOIRE_DES_MATERIAUX_GRANULATS_MARINS", "", "", "","http://geoservices.brgm.fr/odmgm", "", "", ""])
sources.append(["connections-wms", "FRANCE_BRGM_RISQUES_NATURELS_ET_INDUSTRIELS", "", "", "","http://geoservices.brgm.fr/risques", "", "", ""])
sources.append(["connections-wms", "FRANCE_CADASTRE_MINIER", "", "", "","http://ws.carmen.developpement-durable.gouv.fr/WMS/209/CADASTRE_MINIER_DGALN?", "", "", ""])
sources.append(["connections-wms", "FRANCE_CORINE_LAND_COVER_WMS", "", "", "","http://wxs.ign.fr/corinelandcover/geoportail/r/wms?", "", "", ""])
sources.append(["connections-wms", "FRANCE_DEPARTEMENT_17_CHARENTE_MARITIME_GEOPLATEFORME17", "", "", "","https://geo.geoplateforme17.fr/CG17/wms", "", "", ""])
sources.append(["connections-wms", "FRANCE_DEPARTEMENT_44_LOIRE_ATLANTIQUE_VUE_DU_CIEL", "", "", "","http://services.vuduciel.loire-atlantique.fr/geoserver/ows", "", "", ""])
sources.append(["connections-wms", "FRANCE_DEPARTEMENT_53_MAYENNE_ORTHO2013", "", "", "","https://www.geomayenne.fr/arcgis/services/D53_Ortho2013_HR/MapServer/WMSServer?", "", "", ""])
sources.append(["connections-wms", "FRANCE_DEPARTEMENT_53_MAYENNE_ORTHO2016", "", "", "","https://www.geomayenne.fr/arcgis/services/D53_Ortho2016_HR/MapServer/WMSServer?", "", "", ""])
sources.append(["connections-wms", "FRANCE_DEPARTEMENT_80_SOMME", "", "", "","http://geo.somme.fr/arcgis/services/SIG_CG_SOMME/MapServer/WMSServer", "", "", ""])
sources.append(["connections-wms", "FRANCE_DEPARTEMENT_85_VENDEE_GEOVENDEE", "", "", "","http://carto.geovendee.fr/cgi-bin/mapserv?", "", "", ""])
sources.append(["connections-wms", "FRANCE_DEPARTEMENT_93_SEINE_SAINT_DENIS", "", "", "","http://geoportail93.fr/SERV/DATA/", "", "", ""])
sources.append(["connections-wms", "FRANCE_DEPARTEMENT_94_VAL_DE_MARNE", "", "", "","http://geo.valdemarne.fr/viewer/", "", "", ""])
sources.append(["connections-wms", "FRANCE_DEPARTEMENT_988_NOUVELLE_CALEDONIE_GEOREP_FOND_SIMPLIFIE", "", "", "","http://carto.gouv.nc/arcgis/services/fond_simplifie/MapServer/WMSServer", "", "", ""])
sources.append(["connections-wms", "FRANCE_DEPARTEMENT_988_NOUVELLE_CALEDONIE_GEOREP_PARCELLAIRE_INFORMATISE", "", "", "","http://carto.gouv.nc/arcgis/services/plan_parcellaire_informatise/MapServer/WMSServer", "", "", ""])
sources.append(["connections-wms", "FRANCE_DEPARTEMENT_988_NOUVELLE_CALEDONIE_GEOREP_TOPONYMES", "", "", "","http://carto.gouv.nc/arcgis/services/toponymes/MapServer/WMSServer", "", "", ""])
sources.append(["connections-wms", "FRANCE_DIVERS_ADOUR_GARONNE", "", "", "","http://adour-garonne.eaufrance.fr/servicesOGC?", "", "", ""])
sources.append(["connections-wms", "FRANCE_DIVERS_CESBIO_SUD_OUEST", "", "", "","http://cyan.ups-tlse.fr:8080/geoserver/SudOuest/wms?", "", "", ""])
sources.append(["connections-wms", "FRANCE_ENTREPRISE_SOGEFI", "", "", "","http://ws.sogefi-web.com/wms?", "", "", ""])
sources.append(["connections-wms", "FRANCE_GEOFONCIER", "", "", "","https://api.geofoncier.fr/referentielsoge/ogc/wxs?", "", "", ""])
sources.append(["connections-wms", "FRANCE_GEOPORTAIL_URBANISME", "", "", "","http://wxs-gpu.mongeoportail.ign.fr/externe/vkd1evhid6jdj5h4hkhyzjto/wms/v", "", "", ""])
sources.append(["connections-wms", "FRANCE_GEORISQUES", "", "", "","http://georisques.gouv.fr/services?", "", "", ""])
sources.append(["connections-wms", "FRANCE_GEOSUD", "", "", "","http://ids.equipex-geosud.fr/constellation/WS/wmts/WMTS?Service=WMTS&version=1.0.0&Request=GetCapabilities", "", "", ""])
sources.append(["connections-wms", "FRANCE_GEST_EAU", "", "", "","http://gesteau.oieau.fr/service", "", "", ""])
sources.append(["connections-wms", "FRANCE_GISSOL", "", "", "","https://agroenvgeo.data.inra.fr/geoserver/gissol_rmqs/wms?", "", "", ""])
sources.append(["connections-wms", "FRANCE_IFREMER_BIOLOGIE", "", "", "","http://www.ifremer.fr/services/wms/biologie", "", "", ""])
sources.append(["connections-wms", "FRANCE_IFREMER_CHARM2", "", "", "","http://www.ifremer.fr/services/wms_charm", "", "", ""])
sources.append(["connections-wms", "FRANCE_IFREMER_CHARM3", "", "", "","http://www.ifremer.fr/services/wms_charm3", "", "", ""])
sources.append(["connections-wms", "FRANCE_IFREMER_EUROSHELL", "", "", "","http://www.ifremer.fr/services/wms/euroshell", "", "", ""])
sources.append(["connections-wms", "FRANCE_IFREMER_EXPLOITATION_DE_LA_MER", "", "", "","http://www.ifremer.fr/services/wms1", "", "", ""])
sources.append(["connections-wms", "FRANCE_IFREMER_GRANULATS_MARINS", "", "", "","http://www.ifremer.fr/services/wms/granulats_marins", "", "", ""])
sources.append(["connections-wms", "FRANCE_IFREMER_MIMEL", "", "", "","http://www.ifremer.fr/services/wms_mimel", "", "", ""])
sources.append(["connections-wms", "FRANCE_IFREMER_OBSERVATOIRE_PELAGIS", "", "", "","http://www.ifremer.fr/services/wms/observatoire_pelagis", "", "", ""])
sources.append(["connections-wms", "FRANCE_IFREMER_OCEANOGRAPHIE_PHYSIQUE", "", "", "","http://www.ifremer.fr/services/wms/oceanographie_physique", "", "", ""])
sources.append(["connections-wms", "FRANCE_IFREMER_OGIVE_AGIL", "", "", "","http://www.ifremer.fr/services/wms/ogive_agil", "", "", ""])
sources.append(["connections-wms", "FRANCE_IFREMER_PHOTOS_ANCIENNES", "", "", "","http://www.ifremer.fr/services/photos_anciennes", "", "", ""])
sources.append(["connections-wms", "FRANCE_IFREMER_SURVEILLANCE_LITTORALE", "", "", "","http://www.ifremer.fr/services/wms/surveillance_littorale", "", "", ""])
sources.append(["connections-wms", "FRANCE_IGN_CHOISIRGEOPORTAIL_RASTER_WMS", "", "", "","https://wxs.ign.fr/choisirgeoportail/geoportail/r/wms?VERSION=1.3.0", "", "", ""])
sources.append(["connections-wms", "FRANCE_IGN_CHOISIRGEOPORTAIL_VECTEUR_WMS", "", "", "","https://wxs.ign.fr/choisirgeoportail/geoportail/v/wms?VERSION=1.3.0", "", "", ""])
sources.append(["connections-wms", "FRANCE_IGN_CHOISIRGEOPORTAIL_WMTS", "", "", "","https://wxs.ign.fr/choisirgeoportail/geoportail/wmts?SERVICE=WMTS&VERSION=1.0.0&REQUEST=GetCapabilities", "", "", ""])
sources.append(["connections-wms", "FRANCE_IGN_PRATIQUE_WMTS", "", "", "","https://wxs.ign.fr/pratique/geoportail/wmts?SERVICE=WMTS&REQUEST=GetCapabilities", "", "", ""])
sources.append(["connections-wms", "FRANCE_METROPOLE_GRAND_LYON", "", "", "","https://download.data.grandlyon.com/wms/rdata", "", "", ""])
sources.append(["connections-wms", "FRANCE_METROPOLE_GRAND_POITIERS", "", "", "","https://sig.grandpoitiers.fr/arcgis/services/Geoportail/WMS_Preview/MapServer/WmsServer?", "", "", ""])
sources.append(["connections-wms", "FRANCE_MNHN_ECOZONES", "", "", "","http://ws.carmencarto.fr/WMS/119/fxx_ref", "", "", ""])
sources.append(["connections-wms", "FRANCE_MNHN_GRILLE_GUADELOUPE", "", "", "","http://ws.carmencarto.fr/WMS/119/glp_grille?", "", "", ""])
sources.append(["connections-wms", "FRANCE_MNHN_GRILLE_MARTINIQUE", "", "", "","http://ws.carmencarto.fr/WMS/119/mtq_grille?", "", "", ""])
sources.append(["connections-wms", "FRANCE_MNHN_GRILLE_MAYOTTE", "", "", "","http://ws.carmencarto.fr/WMS/119/myt_grille?", "", "", ""])
sources.append(["connections-wms", "FRANCE_MNHN_GRILLE_METROPOLE", "", "", "","http://ws.carmencarto.fr/WMS/119/fxx_grille?", "", "", ""])
sources.append(["connections-wms", "FRANCE_MNHN_GRILLE_REUNION", "", "", "","http://ws.carmencarto.fr/WMS/119/reu_grille?", "", "", ""])
sources.append(["connections-wms", "FRANCE_MNHN_GRILLE_SAINT_BARTHELEMY", "", "", "","http://ws.carmencarto.fr/WMS/119/blm_grille?", "", "", ""])
sources.append(["connections-wms", "FRANCE_MNHN_GRILLE_SAINT_GUYANE", "", "", "","http://ws.carmencarto.fr/WMS/119/guf_grille?", "", "", ""])
sources.append(["connections-wms", "FRANCE_MNHN_GRILLE_SAINT_PIERRE_ET_MIQUELON", "", "", "","http://ws.carmencarto.fr/WMS/119/spm_grille?", "", "", ""])
sources.append(["connections-wms", "FRANCE_MNHN_GRILLE_TAAF_ILES_EPARSES", "", "", "","http://ws.carmencarto.fr/WMS/119/epa_grille?", "", "", ""])
sources.append(["connections-wms", "FRANCE_MNHN_GRILLE_TAAF_ILES_SUBANTARCTIQUES", "", "", "","http://ws.carmencarto.fr/WMS/119/taaf_grille?", "", "", ""])
sources.append(["connections-wms", "FRANCE_MNHN_INPN", "", "", "","http://ws.carmencarto.fr/WMS/119/fxx_inpn", "", "", ""])
sources.append(["connections-wms", "FRANCE_MNHN_REGIONS_BIOGEOGRAPHIQUES_METROPOLE", "", "", "","http://ws.carmencarto.fr/WMS/119/fxx_ref?", "", "", ""])
sources.append(["connections-wms", "FRANCE_MNHN_ZONAGES_GUADELOUPE", "", "", "","http://ws.carmencarto.fr/WMS/119/glp_inpn?", "", "", ""])
sources.append(["connections-wms", "FRANCE_MNHN_ZONAGES_GUYANE", "", "", "","http://ws.carmencarto.fr/WMS/119/guf_inpn?", "", "", ""])
sources.append(["connections-wms", "FRANCE_MNHN_ZONAGES_MAYOTTE", "", "", "","http://ws.carmencarto.fr/WMS/119/myt_inpn?", "", "", ""])
sources.append(["connections-wms", "FRANCE_MNHN_ZONAGES_METROPOLE", "", "", "","http://ws.carmencarto.fr/WMS/119/fxx_inpn?", "", "", ""])
sources.append(["connections-wms", "FRANCE_MNHN_ZONAGES_REUNION", "", "", "","http://ws.carmencarto.fr/WMS/119/reu_inpn?", "", "", ""])
sources.append(["connections-wms", "FRANCE_MNHN_ZONAGES_SAINT_PIERRE_ET_MIQUELON", "", "", "","http://ws.carmencarto.fr/WMS/119/spm_inpn?", "", "", ""])
sources.append(["connections-wms", "FRANCE_ONF_FORETS", "", "", "","http://ws.carmencarto.fr/WMS/105/ONF_Forets", "", "", ""])
sources.append(["connections-wms", "FRANCE_REGION_CRAIG_MEMBRES", "", "", "","http://ids.craig.fr/wxs/membres/wms", "", "", ""])
sources.append(["connections-wms", "FRANCE_REGION_CRAIG_MNT", "", "", "","http://wms.craig.fr/mnt", "", "", ""])
sources.append(["connections-wms", "FRANCE_REGION_CRAIG_ORTHO", "", "", "","http://wms.craig.fr/ortho", "", "", ""])
sources.append(["connections-wms", "FRANCE_REGION_CRAIG_ORTHO_TUILE", "", "", "","http://tiles.craig.fr/ortho/service?", "", "", ""])
sources.append(["connections-wms", "FRANCE_REGION_CRAIG_PUBLIC", "", "", "","http://ids.craig.fr/wxs/public/wms", "", "", ""])
sources.append(["connections-wms", "FRANCE_REGION_DREAL_ALSACE_CARTE", "", "", "","http://ws.carmen.developpement-durable.gouv.fr/WMS/5/Carte_Alsace?", "", "", ""])
sources.append(["connections-wms", "FRANCE_REGION_DREAL_ALSACE_DI_MULHOUSE_APPROUVE?", "", "", "","http://ws.carmen.developpement-durable.gouv.fr/WMS/5/carte_DI_MULHOUSE_APPROUVE?", "", "", ""])
sources.append(["connections-wms", "FRANCE_REGION_DREAL_ALSACE_SRCE", "", "", "","http://ws.carmen.developpement-durable.gouv.fr/WMS/5/Carte_Alsace_SRCE?", "", "", ""])
sources.append(["connections-wms", "FRANCE_REGION_DREAL_BRETAGNE_EAU", "", "", "","http://ws.carmen.developpement-durable.gouv.fr/WMS/10/EAU?", "", "", ""])
sources.append(["connections-wms", "FRANCE_REGION_DREAL_BRETAGNE_NATURE_PAYSAGE", "", "", "","http://ws.carmen.developpement-durable.gouv.fr/WMS/10/Nature_Paysage?", "", "", ""])
sources.append(["connections-wms", "FRANCE_REGION_DREAL_BRETAGNE_RISQUE", "", "", "","http://ws.carmen.developpement-durable.gouv.fr/WMS/10/Risque?", "", "", ""])
sources.append(["connections-wms", "FRANCE_REGION_DREAL_CENTRE_BASSIN_LOIRE_BRETAGNE", "", "", "","http://ws.carmen.developpement-durable.gouv.fr/WMS/11/eau_bassin1?", "", "", ""])
sources.append(["connections-wms", "FRANCE_REGION_DREAL_CENTRE_BLOIS", "", "", "","http://ws.carmen.developpement-durable.gouv.fr/WMS/11/blois?", "", "", ""])
sources.append(["connections-wms", "FRANCE_REGION_DREAL_CENTRE_CONNAISSANCE_BASSIN", "", "", "","http://ws.carmen.developpement-durable.gouv.fr/WMS/11/eau_bassin_connaissance?", "", "", ""])
sources.append(["connections-wms", "FRANCE_REGION_DREAL_CENTRE_DREAL", "", "", "","http://ws.carmen.developpement-durable.gouv.fr/WMS/11/DREAL24?", "", "", ""])
sources.append(["connections-wms", "FRANCE_REGION_DREAL_CENTRE_EAU_BASSIN_TRI", "", "", "","http://ws.carmen.developpement-durable.gouv.fr/WMS/11/eau_bassin_tri?", "", "", ""])
sources.append(["connections-wms", "FRANCE_REGION_DREAL_CENTRE_L214_CONSULTATION", "", "", "","http://ws.carmen.developpement-durable.gouv.fr/WMS/11/eau_bassin_L214_consultation2?", "", "", ""])
sources.append(["connections-wms", "FRANCE_REGION_DREAL_CENTRE_ORLEANS", "", "", "","http://ws.carmen.developpement-durable.gouv.fr/WMS/11/orleans?", "", "", ""])
sources.append(["connections-wms", "FRANCE_REGION_DREAL_CENTRE_PHEC_CHER_NIEVRE", "", "", "","http://ws.carmen.developpement-durable.gouv.fr/WMS/11/PHEC_CHER_NIEVRE?", "", "", ""])
sources.append(["connections-wms", "FRANCE_REGION_DREAL_CENTRE_REPERES_DE_CRUE", "", "", "","http://ws.carmen.developpement-durable.gouv.fr/WMS/11/reperes_crue?", "", "", ""])
sources.append(["connections-wms", "FRANCE_REGION_DREAL_CENTRE_RZP", "", "", "","http://ws.carmen.developpement-durable.gouv.fr/WMS/11/rzp_bassin?", "", "", ""])
sources.append(["connections-wms", "FRANCE_REGION_DREAL_CENTRE_SDPC", "", "", "","http://ws.carmen.developpement-durable.gouv.fr/WMS/11/eau_bassin_sdpc?", "", "", ""])
sources.append(["connections-wms", "FRANCE_REGION_DREAL_CENTRE_TOURS", "", "", "","http://ws.carmen.developpement-durable.gouv.fr/WMS/11/tours?", "", "", ""])
sources.append(["connections-wms", "FRANCE_REGION_DREAL_HAUTE_NORMANDIE_TRI_DIEPPE", "", "", "","http://ws.carmen.developpement-durable.gouv.fr/WMS/17/TRI_Dieppe?", "", "", ""])
sources.append(["connections-wms", "FRANCE_REGION_DREAL_HAUTE_NORMANDIE_TRI_EVREUX", "", "", "","http://ws.carmen.developpement-durable.gouv.fr/WMS/17/TRI_Evreux?", "", "", ""])
sources.append(["connections-wms", "FRANCE_REGION_DREAL_HAUTE_NORMANDIE_TRI_LE_HAVRE", "", "", "","http://ws.carmen.developpement-durable.gouv.fr/WMS/17/TRI_Le_Havre?", "", "", ""])
sources.append(["connections-wms", "FRANCE_REGION_DREAL_HAUTE_NORMANDIE_TRI_ROUEN", "", "", "","http://ws.carmen.developpement-durable.gouv.fr/WMS/17/TRI_Rouen?", "", "", ""])
sources.append(["connections-wms", "FRANCE_REGION_DREAL_LORRAINE_CARTE_GLOBALE", "", "", "","http://ws.carmen.developpement-durable.gouv.fr/WMS/21/carte_globale_lorraine?", "", "", ""])
sources.append(["connections-wms", "FRANCE_REGION_DREAL_LORRAINE_DI_TRI_DIE", "", "", "","http://ws.carmen.developpement-durable.gouv.fr/WMS/21/carte_DI_TRI_DIE?", "", "", ""])
sources.append(["connections-wms", "FRANCE_REGION_DREAL_LORRAINE_DI_TRI_EPIN", "", "", "","http://ws.carmen.developpement-durable.gouv.fr/WMS/21/carte_DI_TRI_EPIN?", "", "", ""])
sources.append(["connections-wms", "FRANCE_REGION_DREAL_LORRAINE_DI_TRI_LONG", "", "", "","http://ws.carmen.developpement-durable.gouv.fr/WMS/21/carte_DI_TRI_LONG?", "", "", ""])
sources.append(["connections-wms", "FRANCE_REGION_DREAL_LORRAINE_DI_TRI_METZ", "", "", "","http://ws.carmen.developpement-durable.gouv.fr/WMS/21/carte_DI_TRI_METZ?", "", "", ""])
sources.append(["connections-wms", "FRANCE_REGION_DREAL_LORRAINE_DI_TRI_NANC", "", "", "","http://ws.carmen.developpement-durable.gouv.fr/WMS/21/carte_DI_TRI_NANC?", "", "", ""])
sources.append(["connections-wms", "FRANCE_REGION_DREAL_LORRAINE_DI_TRI_NEUF", "", "", "","http://ws.carmen.developpement-durable.gouv.fr/WMS/21/carte_DI_TRI_NEUF?", "", "", ""])
sources.append(["connections-wms", "FRANCE_REGION_DREAL_LORRAINE_DI_TRI_PONT", "", "", "","http://ws.carmen.developpement-durable.gouv.fr/WMS/21/carte_DI_TRI_PONT?", "", "", ""])
sources.append(["connections-wms", "FRANCE_REGION_DREAL_LORRAINE_DI_TRI_SARR", "", "", "","http://ws.carmen.developpement-durable.gouv.fr/WMS/21/carte_DI_TRI_SARR?", "", "", ""])
sources.append(["connections-wms", "FRANCE_REGION_DREAL_LORRAINE_DI_TRI_SEDA", "", "", "","http://ws.carmen.developpement-durable.gouv.fr/WMS/21/carte_DI_TRI_SEDA?", "", "", ""])
sources.append(["connections-wms", "FRANCE_REGION_DREAL_LORRAINE_DI_TRI_VERD", "", "", "","http://ws.carmen.developpement-durable.gouv.fr/WMS/21/carte_DI_TRI_VERD?", "", "", ""])
sources.append(["connections-wms", "FRANCE_REGION_DREAL_LORRAINE_N2000_GRANDE_REGION", "", "", "","http://ws.carmen.developpement-durable.gouv.fr/WMS/21/carte_n2000_grande_region?", "", "", ""])
sources.append(["connections-wms", "FRANCE_REGION_DREAL_LORRAINE_ZONES_HUMIDES", "", "", "","http://ws.carmen.developpement-durable.gouv.fr/WMS/21/carte_zones_humides_lorraine?", "", "", ""])
sources.append(["connections-wms", "FRANCE_REGION_DREAL_PACA_ENVIRONNMENT_INDUSTRIE_RISQUES", "", "", "","http://ws.carmen.developpement-durable.gouv.fr/WMS/25/environnement?", "", "", ""])
sources.append(["connections-wms", "FRANCE_REGION_GEOBRETAGNE", "", "", "","http://geobretagne.fr/geoserver/wms?", "", "", ""])
sources.append(["connections-wms", "FRANCE_REGION_GEOBRETAGNE_CADASTRE", "", "", "","http://geobretagne.fr/geoserver/cadastre/wms", "", "", ""])
sources.append(["connections-wms", "FRANCE_REGION_GEOBRETAGNE_DRAAF", "", "", "","http://geobretagne.fr/geoserver/draaf/wms?", "", "", ""])
sources.append(["connections-wms", "FRANCE_REGION_GEOBRETAGNE_DREAL", "", "", "","http://geobretagne.fr/geoserver/dreal_b/wms", "", "", ""])
sources.append(["connections-wms", "FRANCE_REGION_GEOBRETAGNE_OSM", "", "", "","http://geobretagne.fr/geoserver/osm/wms", "", "", ""])
sources.append(["connections-wms", "FRANCE_REGION_GEOBRETAGNE_PHOTO", "", "", "","http://geobretagne.fr/geoserver/photo/wms", "", "", ""])
sources.append(["connections-wms", "FRANCE_REGION_GEOBRETAGNE_REF", "", "", "","http://geobretagne.fr/geoserver/ref/wms", "", "", ""])
sources.append(["connections-wms", "FRANCE_REGION_GEOBRETAGNE_SIGN_ADRESSE", "", "", "","http://ows.region-bretagne.fr/geoserver/edit_rb/wms", "", "", ""])
sources.append(["connections-wms", "FRANCE_REGION_GEOGUYANE", "", "", "","https://carto.geoguyane.fr/cgi-bin/mapserv?", "", "", ""])
sources.append(["connections-wms", "FRANCE_REGION_GEOPICARDIE", "", "", "","http://www.geopicardie.fr/geoserver/geopicardie/ows", "", "", ""])
sources.append(["connections-wms", "FRANCE_REGION_GEOPICARDIE_02_AISNE", "", "", "","http://www.geopicardie.fr/geoserver/dept02/ows", "", "", ""])
sources.append(["connections-wms", "FRANCE_REGION_GEOPICARDIE_60_OISE", "", "", "","http://www.geopicardie.fr/geoserver/dept60/ows", "", "", ""])
sources.append(["connections-wms", "FRANCE_REGION_GEOPICARDIE_DONNEES_REGIONALES", "", "", "","http://www.geopicardie.fr/geoserver/reg22/ows", "", "", ""])
sources.append(["connections-wms", "FRANCE_REGION_GIP_BRETAGNE_ENVIRONNEMENT", "", "", "","http://geobretagne.fr/geoserver/bretagneenvironnement/wms", "", "", ""])
sources.append(["connections-wms", "FRANCE_REGION_GUYANE_SIG_ADMINISTRATIF", "", "", "","https://catalogue.guyane-sig.fr/geoserver/administratif/wms", "", "", ""])
sources.append(["connections-wms", "FRANCE_REGION_GUYANE_SIG_ALTIMETRIE", "", "", "","https://catalogue.guyane-sig.fr/geoserver/altimetrie/wms", "", "", ""])
sources.append(["connections-wms", "FRANCE_REGION_GUYANE_SIG_CADASTRE", "", "", "","https://catalogue.guyane-sig.fr/geoserver/cadastre/wms", "", "", ""])
sources.append(["connections-wms", "FRANCE_REGION_GUYANE_SIG_DOCUMENTS_URBANISME", "", "", "","https://catalogue.guyane-sig.fr/geoserver/du/wms", "", "", ""])
sources.append(["connections-wms", "FRANCE_REGION_GUYANE_SIG_ECONOMIE", "", "", "","https://catalogue.guyane-sig.fr/geoserver/economie/wms", "", "", ""])
sources.append(["connections-wms", "FRANCE_REGION_GUYANE_SIG_EQUIPEMENTS_ET_SERVICES_PUBLICS", "", "", "","https://catalogue.guyane-sig.fr/geoserver/esp/wms", "", "", ""])
sources.append(["connections-wms", "FRANCE_REGION_GUYANE_SIG_IGN", "", "", "","https://catalogue.guyane-sig.fr/geoserver/ign/wms", "", "", ""])
sources.append(["connections-wms", "FRANCE_REGION_GUYANE_SIG_ORTHO", "", "", "","https://catalogue.guyane-sig.fr/geoserver/ortho/wms", "", "", ""])
sources.append(["connections-wms", "FRANCE_REGION_GUYANE_SIG_OSM", "", "", "","https://catalogue.guyane-sig.fr/geoserver/osm/wms", "", "", ""])
sources.append(["connections-wms", "FRANCE_REGION_GUYANE_SIG_SEAS", "", "", "","https://catalogue.guyane-sig.fr/geoserver/seas_2/wms", "", "", ""])
sources.append(["connections-wms", "FRANCE_REGION_GUYANE_SIG_WMTS", "", "", "","https://catalogue.guyane-sig.fr/geoserver/gwc/service/wmts", "", "", ""])
sources.append(["connections-wms", "FRANCE_REGION_PIGMA_CG47", "", "", "","https://www.pigma.org/geoserver/cg47/wms", "", "", ""])
sources.append(["connections-wms", "FRANCE_REGION_PIGMA_DRAC", "", "", "","https://www.pigma.org/geoserver/drac/wms", "", "", ""])
sources.append(["connections-wms", "FRANCE_REGION_PIGMA_RECTORAT", "", "", "","https://www.pigma.org/geoserver/rect/wms", "", "", ""])
sources.append(["connections-wms", "FRANCE_REGION_PIGMA_RFF", "", "", "","https://www.pigma.org/geoserver/rff/wms", "", "", ""])
sources.append(["connections-wms", "FRANCE_REGION_PPIGE_NPDC", "", "", "","https://www.ppige-npdc.fr/geoserver/ows", "", "", ""])
sources.append(["connections-wms", "FRANCE_RESEAU_ZONES_HUMIDES", "", "", "","http://wms.reseau-zones-humides.org/cgi-bin/wmsfma", "", "", ""])
sources.append(["connections-wms", "FRANCE_SANDRE", "", "", "","https://services.sandre.eaufrance.fr/geo/sandre", "", "", ""])
sources.append(["connections-wms", "FRANCE_SANDRE_STATIONS_DE_MESURE", "", "", "","http://services.sandre.eaufrance.fr/geo/stations", "", "", ""])
sources.append(["connections-wms", "FRANCE_SANDRE_ZONAGE", "", "", "","http://services.sandre.eaufrance.fr/geo/zonage", "", "", ""])
sources.append(["connections-wms", "FRANCE_SHOM_INSPIRE", "", "", "","http://services.data.shom.fr/INSPIRE/wms/r", "", "", ""])
sources.append(["connections-wms", "FRANCE_SHOM_INSPIRE_TUILE", "", "", "","http://services.data.shom.fr/INSPIRE/wmts", "", "", ""])
sources.append(["connections-wms", "MONDE_GEBCO_GLOBAL", "", "", "","https://www.gebco.net/data_and_products/gebco_web_services/web_map_service/mapserv?", "", "", ""])
sources.append(["connections-wms", "MONDE_GEBCO_POLE_NORD", "", "", "","https://www.gebco.net/data_and_products/gebco_web_services/north_polar_view_wms/mapserv?", "", "", ""])
sources.append(["connections-wms", "MONDE_GEBCO_POLE_SUD", "", "", "","https://www.gebco.net/data_and_products/gebco_web_services/south_polar_view_wms/mapserv?", "", "", ""])
sources.append(["connections-wms", "MONDE_NASA", "", "", "","http://neowms.sci.gsfc.nasa.gov/wms/wms?", "", "", ""])
# QGIS_WFS.xml
sources.append(["connections-wfs", "FRANCE_BRGM_GEOLOGIE_HYDROGEOLOGIE_GRAVIMETRIE", "", "", "","http://geoservices.brgm.fr/geologie", "", "", ""])
sources.append(["connections-wfs", "FRANCE_BRGM_OBSERVATOIRE_DES_MATERIAUX_GRANULATS_MARINS", "", "", "","http://geoservices.brgm.fr/odmgm", "", "", ""])
sources.append(["connections-wfs", "FRANCE_BRGM_RISQUES_NATURELS_ET_INDUSTRIELS", "", "", "","http://geoservices.brgm.fr/risques", "", "", ""])
sources.append(["connections-wfs", "FRANCE_CADASTRE_MINIER", "", "", "","http://ws.carmen.developpement-durable.gouv.fr/WFS/209/CADASTRE_MINIER_DGALN?", "", "", ""])
sources.append(["connections-wfs", "FRANCE_CORINE_LAND_COVER", "", "", "","http://wxs.ign.fr/corinelandcover/geoportail/wfs?", "", "", ""])
sources.append(["connections-wfs", "FRANCE_DEPARTEMENT_17_CHARENTE_MARITIME_GEOPLATEFORME17", "", "", "","https://geo.geoplateforme17.fr/CG17/wfs", "", "", ""])
sources.append(["connections-wfs", "FRANCE_DEPARTEMENT_80_SOMME", "", "", "","http://geo.somme.fr/arcgis/services/SIG_CG_SOMME/MapServer/WFSServer", "", "", ""])
sources.append(["connections-wfs", "FRANCE_DEPARTEMENT_85_VENDEE_GEOVENDEE", "", "", "","http://carto.geovendee.fr/cgi-bin/mapservwfs?", "", "", ""])
sources.append(["connections-wfs", "FRANCE_DEPARTEMENT_93_SEINE_SAINT_DENIS", "", "", "","http://geoportail93.fr/SERV/DATA/", "", "", ""])
sources.append(["connections-wfs", "FRANCE_DEPARTEMENT_94_VAL_DE_MARNE", "", "", "","http://geo.valdemarne.fr/viewer/", "", "", ""])
sources.append(["connections-wfs", "FRANCE_DIVERS_ADOUR_GARONNE", "", "", "","http://adour-garonne.eaufrance.fr/servicesOGC?", "", "", ""])
sources.append(["connections-wfs", "FRANCE_GEOPORTAIL_URBANISME", "", "", "","http://wxs-gpu.mongeoportail.ign.fr/externe/39wtxmgtn23okfbbs1al2lz3/wfs", "", "", ""])
sources.append(["connections-wfs", "FRANCE_GEORISQUES", "", "", "","http://georisques.gouv.fr/services?", "", "", ""])
sources.append(["connections-wfs", "FRANCE_GEST_EAU", "", "", "","http://gesteau.eaufrance.fr/service?VERSION=1.1.0", "", "", ""])
sources.append(["connections-wfs", "FRANCE_GISSOL", "", "", "","https://agroenvgeo.data.inra.fr/geoserver/gissol_rmqs/wms?", "", "", ""])
sources.append(["connections-wfs", "FRANCE_IFREMER_BIOLOGIE", "", "", "","http://www.ifremer.fr/services/wfs/biologie", "", "", ""])
sources.append(["connections-wfs", "FRANCE_IFREMER_GRANULATS_MARINS", "", "", "","http://www.ifremer.fr/services/wfs/granulats_marins", "", "", ""])
sources.append(["connections-wfs", "FRANCE_IFREMER_SURVEILLANCE_LITTORALE", "", "", "","http://www.ifremer.fr/services/wfs/surveillance_littorale", "", "", ""])
sources.append(["connections-wfs", "FRANCE_IGN_CHOISIRGEOPORTAIL_WFS", "", "", "","https://wxs.ign.fr/choisirgeoportail/geoportail/wfs?VERSION=2.0.0", "", "", ""])
sources.append(["connections-wfs", "FRANCE_METROPOLE_GRAND_LYON_grandlyon", "", "", "","https://download.data.grandlyon.com/wfs/grandlyon", "", "", ""])
sources.append(["connections-wfs", "FRANCE_METROPOLE_GRAND_LYON_rdata", "", "", "","https://download.data.grandlyon.com/wfs/rdata", "", "", ""])
sources.append(["connections-wfs", "FRANCE_MNHN_GRILLE_GUADELOUPE", "", "", "","http://ws.carmencarto.fr/WFS/119/glp_grille?", "", "", ""])
sources.append(["connections-wfs", "FRANCE_MNHN_GRILLE_MARTINIQUE", "", "", "","http://ws.carmencarto.fr/WFS/119/mtq_grille?", "", "", ""])
sources.append(["connections-wfs", "FRANCE_MNHN_GRILLE_MAYOTTE", "", "", "","http://ws.carmencarto.fr/WFS/119/myt_grille?", "", "", ""])
sources.append(["connections-wfs", "FRANCE_MNHN_GRILLE_METROPOLE", "", "", "","http://ws.carmencarto.fr/WFS/119/fxx_grille?", "", "", ""])
sources.append(["connections-wfs", "FRANCE_MNHN_GRILLE_REUNION", "", "", "","http://ws.carmencarto.fr/WFS/119/reu_grille?", "", "", ""])
sources.append(["connections-wfs", "FRANCE_MNHN_GRILLE_SAINT_BARTHELEMY", "", "", "","http://ws.carmencarto.fr/WFS/119/blm_grille?", "", "", ""])
sources.append(["connections-wfs", "FRANCE_MNHN_GRILLE_SAINT_GUYANE", "", "", "","http://ws.carmencarto.fr/WFS/119/guf_grille?", "", "", ""])
sources.append(["connections-wfs", "FRANCE_MNHN_GRILLE_SAINT_PIERRE_ET_MIQUELON", "", "", "","http://ws.carmencarto.fr/WFS/119/spm_grille?", "", "", ""])
sources.append(["connections-wfs", "FRANCE_MNHN_GRILLE_TAAF_ILES_EPARSES", "", "", "","http://ws.carmencarto.fr/WFS/119/epa_grille?", "", "", ""])
sources.append(["connections-wfs", "FRANCE_MNHN_GRILLE_TAAF_ILES_SUBANTARCTIQUES", "", "", "","http://ws.carmencarto.fr/WFS/119/taaf_grille?", "", "", ""])
sources.append(["connections-wfs", "FRANCE_MNHN_REGIONS_BIOGEOGRAPHIQUES_METROPOLE", "", "", "","http://ws.carmencarto.fr/WFS/119/fxx_ref?", "", "", ""])
sources.append(["connections-wfs", "FRANCE_MNHN_ZONAGES_GUADELOUPE", "", "", "","http://ws.carmencarto.fr/WFS/119/glp_inpn?", "", "", ""])
sources.append(["connections-wfs", "FRANCE_MNHN_ZONAGES_GUYANE", "", "", "","http://ws.carmencarto.fr/WFS/119/guf_inpn?", "", "", ""])
sources.append(["connections-wfs", "FRANCE_MNHN_ZONAGES_MAYOTTE", "", "", "","http://ws.carmencarto.fr/WFS/119/myt_inpn?", "", "", ""])
sources.append(["connections-wfs", "FRANCE_MNHN_ZONAGES_METROPOLE", "", "", "","http://ws.carmencarto.fr/WFS/119/fxx_inpn?", "", "", ""])
sources.append(["connections-wfs", "FRANCE_MNHN_ZONAGES_REUNION", "", "", "","http://ws.carmencarto.fr/WFS/119/reu_inpn?", "", "", ""])
sources.append(["connections-wfs", "FRANCE_MNHN_ZONAGES_SAINT_PIERRE_ET_MIQUELON", "", "", "","http://ws.carmencarto.fr/WFS/119/spm_inpn?", "", "", ""])
sources.append(["connections-wfs", "FRANCE_ONF_FORETS", "", "", "","http://ws.carmencarto.fr/WFS/105/ONF_Forets", "", "", ""])
sources.append(["connections-wfs", "FRANCE_REGION_CRAIG_MEMBRES", "", "", "","http://ids.craig.fr/wxs/membres/wfs", "", "", ""])
sources.append(["connections-wfs", "FRANCE_REGION_CRAIG_PUBLIC", "", "", "","http://ids.craig.fr/wxs/public/wfs", "", "", ""])
sources.append(["connections-wfs", "FRANCE_REGION_DREAL_ALSACE_CARTE", "", "", "","http://ws.carmen.developpement-durable.gouv.fr/WFS/5/Carte_Alsace?", "", "", ""])
sources.append(["connections-wfs", "FRANCE_REGION_DREAL_ALSACE_DI_MULHOUSE_APPROUVE?", "", "", "","http://ws.carmen.developpement-durable.gouv.fr/WFS/5/carte_DI_MULHOUSE_APPROUVE?", "", "", ""])
sources.append(["connections-wfs", "FRANCE_REGION_DREAL_ALSACE_SRCE", "", "", "","http://ws.carmen.developpement-durable.gouv.fr/WFS/5/Carte_Alsace_SRCE?", "", "", ""])
sources.append(["connections-wfs", "FRANCE_REGION_DREAL_BRETAGNE_EAU", "", "", "","http://ws.carmen.developpement-durable.gouv.fr/WFS/10/EAU?", "", "", ""])
sources.append(["connections-wfs", "FRANCE_REGION_DREAL_BRETAGNE_NATURE_PAYSAGE", "", "", "","http://ws.carmen.developpement-durable.gouv.fr/WFS/10/Nature_Paysage?", "", "", ""])
sources.append(["connections-wfs", "FRANCE_REGION_DREAL_BRETAGNE_RISQUE", "", "", "","http://ws.carmen.developpement-durable.gouv.fr/WFS/10/Risque?", "", "", ""])
sources.append(["connections-wfs", "FRANCE_REGION_DREAL_CENTRE_BASSIN_LOIRE_BRETAGNE", "", "", "","http://ws.carmen.developpement-durable.gouv.fr/WFS/11/eau_bassin1?", "", "", ""])
sources.append(["connections-wfs", "FRANCE_REGION_DREAL_CENTRE_BLOIS", "", "", "","http://ws.carmen.developpement-durable.gouv.fr/WFS/11/blois?", "", "", ""])
sources.append(["connections-wfs", "FRANCE_REGION_DREAL_CENTRE_DREAL", "", "", "","http://ws.carmen.developpement-durable.gouv.fr/WFS/11/DREAL24?", "", "", ""])
sources.append(["connections-wfs", "FRANCE_REGION_DREAL_CENTRE_EAU_BASSIN_TRI", "", "", "","http://ws.carmen.developpement-durable.gouv.fr/WFS/11/eau_bassin_tri?", "", "", ""])
sources.append(["connections-wfs", "FRANCE_REGION_DREAL_CENTRE_L214_CONSULTATION", "", "", "","http://ws.carmen.developpement-durable.gouv.fr/WFS/11/eau_bassin_L214_consultation2?", "", "", ""])
sources.append(["connections-wfs", "FRANCE_REGION_DREAL_CENTRE_ORLEANS", "", "", "","http://ws.carmen.developpement-durable.gouv.fr/WFS/11/orleans?", "", "", ""])
sources.append(["connections-wfs", "FRANCE_REGION_DREAL_CENTRE_PHEC_CHER_NIEVRE", "", "", "","http://ws.carmen.developpement-durable.gouv.fr/WFS/11/PHEC_CHER_NIEVRE?", "", "", ""])
sources.append(["connections-wfs", "FRANCE_REGION_DREAL_CENTRE_REPERES_DE_CRUE", "", "", "","http://ws.carmen.developpement-durable.gouv.fr/WFS/11/reperes_crue?", "", "", ""])
sources.append(["connections-wfs", "FRANCE_REGION_DREAL_CENTRE_RZP", "", "", "","http://ws.carmen.developpement-durable.gouv.fr/WFS/11/rzp_bassin?", "", "", ""])
sources.append(["connections-wfs", "FRANCE_REGION_DREAL_CENTRE_SDPC", "", "", "","http://ws.carmen.developpement-durable.gouv.fr/WFS/11/eau_bassin_sdpc?", "", "", ""])
sources.append(["connections-wfs", "FRANCE_REGION_DREAL_CENTRE_TOURS", "", "", "","http://ws.carmen.developpement-durable.gouv.fr/WFS/11/tours?", "", "", ""])
sources.append(["connections-wfs", "FRANCE_REGION_DREAL_HAUTE_NORMANDIE_TRI_DIEPPE", "", "", "","http://ws.carmen.developpement-durable.gouv.fr/WFS/17/TRI_Dieppe?", "", "", ""])
sources.append(["connections-wfs", "FRANCE_REGION_DREAL_HAUTE_NORMANDIE_TRI_EVREUX", "", "", "","http://ws.carmen.developpement-durable.gouv.fr/WFS/17/TRI_Evreux?", "", "", ""])
sources.append(["connections-wfs", "FRANCE_REGION_DREAL_HAUTE_NORMANDIE_TRI_LE_HAVRE", "", "", "","http://ws.carmen.developpement-durable.gouv.fr/WFS/17/TRI_Le_Havre?", "", "", ""])
sources.append(["connections-wfs", "FRANCE_REGION_DREAL_HAUTE_NORMANDIE_TRI_ROUEN", "", "", "","http://ws.carmen.developpement-durable.gouv.fr/WFS/17/TRI_Rouen?", "", "", ""])
sources.append(["connections-wfs", "FRANCE_REGION_DREAL_LORRAINE_CARTE_GLOBALE", "", "", "","http://ws.carmen.developpement-durable.gouv.fr/WFS/21/carte_globale_lorraine?", "", "", ""])
sources.append(["connections-wfs", "FRANCE_REGION_DREAL_LORRAINE_DI_TRI_DIE", "", "", "","http://ws.carmen.developpement-durable.gouv.fr/WFS/21/carte_DI_TRI_DIE?", "", "", ""])
sources.append(["connections-wfs", "FRANCE_REGION_DREAL_LORRAINE_DI_TRI_EPIN", "", "", "","http://ws.carmen.developpement-durable.gouv.fr/WFS/21/carte_DI_TRI_EPIN?", "", "", ""])
sources.append(["connections-wfs", "FRANCE_REGION_DREAL_LORRAINE_DI_TRI_LONG", "", "", "","http://ws.carmen.developpement-durable.gouv.fr/WFS/21/carte_DI_TRI_LONG?", "", "", ""])
sources.append(["connections-wfs", "FRANCE_REGION_DREAL_LORRAINE_DI_TRI_METZ", "", "", "","http://ws.carmen.developpement-durable.gouv.fr/WFS/21/carte_DI_TRI_METZ?", "", "", ""])
sources.append(["connections-wfs", "FRANCE_REGION_DREAL_LORRAINE_DI_TRI_NANC", "", "", "","http://ws.carmen.developpement-durable.gouv.fr/WFS/21/carte_DI_TRI_NANC?", "", "", ""])
sources.append(["connections-wfs", "FRANCE_REGION_DREAL_LORRAINE_DI_TRI_NEUF", "", "", "","http://ws.carmen.developpement-durable.gouv.fr/WFS/21/carte_DI_TRI_NEUF?", "", "", ""])
sources.append(["connections-wfs", "FRANCE_REGION_DREAL_LORRAINE_DI_TRI_PONT", "", "", "","http://ws.carmen.developpement-durable.gouv.fr/WFS/21/carte_DI_TRI_PONT?", "", "", ""])
sources.append(["connections-wfs", "FRANCE_REGION_DREAL_LORRAINE_DI_TRI_SARR", "", "", "","http://ws.carmen.developpement-durable.gouv.fr/WFS/21/carte_DI_TRI_SARR?", "", "", ""])
sources.append(["connections-wfs", "FRANCE_REGION_DREAL_LORRAINE_DI_TRI_SEDA", "", "", "","http://ws.carmen.developpement-durable.gouv.fr/WFS/21/carte_DI_TRI_SEDA?", "", "", ""])
sources.append(["connections-wfs", "FRANCE_REGION_DREAL_LORRAINE_DI_TRI_VERD", "", "", "","http://ws.carmen.developpement-durable.gouv.fr/WFS/21/carte_DI_TRI_VERD?", "", "", ""])
sources.append(["connections-wfs", "FRANCE_REGION_DREAL_LORRAINE_N2000_GRANDE_REGION", "", "", "","http://ws.carmen.developpement-durable.gouv.fr/WFS/21/carte_n2000_grande_region?", "", "", ""])
sources.append(["connections-wfs", "FRANCE_REGION_DREAL_LORRAINE_ZONES_HUMIDES", "", "", "","http://ws.carmen.developpement-durable.gouv.fr/WFS/21/carte_zones_humides_lorraine?", "", "", ""])
sources.append(["connections-wfs", "FRANCE_REGION_DREAL_PACA_ENVIRONNMENT_INDUSTRIE_RISQUES", "", "", "","http://ws.carmen.developpement-durable.gouv.fr/WFS/25/environnement?", "", "", ""])
sources.append(["connections-wfs", "FRANCE_REGION_GEOBRETAGNE", "", "", "","http://ows.region-bretagne.fr/geoserver/rb/wfs?", "", "", ""])
sources.append(["connections-wfs", "FRANCE_REGION_GEOGUYANE", "", "", "","https://carto.geoguyane.fr/cgi-bin/mapservwfs?", "", "", ""])
sources.append(["connections-wfs", "FRANCE_REGION_GEOPICARDIE", "", "", "","http://www.geopicardie.fr/geoserver/geopicardie/ows", "", "", ""])
sources.append(["connections-wfs", "FRANCE_REGION_GEOPICARDIE_02_AISNE", "", "", "","http://www.geopicardie.fr/geoserver/dept02/ows", "", "", ""])
sources.append(["connections-wfs", "FRANCE_REGION_GEOPICARDIE_60_OISE", "", "", "","http://www.geopicardie.fr/geoserver/dept60/ows", "", "", ""])
sources.append(["connections-wfs", "FRANCE_REGION_PIGMA", "", "", "","https://www.pigma.org/geoserver/wfs", "", "", ""])
sources.append(["connections-wfs", "FRANCE_REGION_PPIGE", "", "", "","https://www.ppige-npdc.fr/geoserver/ows?", "", "", ""])
sources.append(["connections-wfs", "FRANCE_SANDRE", "", "", "","https://services.sandre.eaufrance.fr/geo/sandre", "", "", ""])
sources.append(["connections-wfs", "FRANCE_SANDRE_MASSES_D_EAU", "", "", "","http://services.sandre.eaufrance.fr/geo/mdo_FXX?VERSION=1.1.0", "", "", ""])
sources.append(["connections-wfs", "FRANCE_SANDRE_REFERENTIEL_HYDRO", "", "", "","http://services.sandre.eaufrance.fr/geo/eth_FXX?VERSION=1.1.0", "", "", ""])
sources.append(["connections-wfs", "FRANCE_SANDRE_STATIONS", "", "", "","http://services.sandre.eaufrance.fr/geo/stq_FXX?VERSION=1.1.0", "", "", ""])
sources.append(["connections-wfs", "FRANCE_SANDRE_ZONAGES", "", "", "","http://services.sandre.eaufrance.fr/geo/zon_FXX?VERSION=1.1.0", "", "", ""])
sources.append(["connections-wfs", "FRANCE_SHOM", "", "", "","http://services.data.shom.fr/INSPIRE/wfs", "", "", ""])
# QGIS_XYZ.xml
sources.append(["connections-xyz", "Bing VirtualEarth", "", "", "","http://ecn.t3.tiles.virtualearth.net/tiles/a{q}.jpeg?g=1", "", "19", "1"])
sources.append(["connections-xyz", "CartoDb Dark Matter", "", "", "Map tiles by CartoDB, under CC BY 3.0. Data by OpenStreetMap, under ODbL.","http://basemaps.cartocdn.com/dark_all/%7Bz%7D/%7Bx%7D/%7By%7D.png", "", "20", "0"])
sources.append(["connections-xyz", "CartoDb Positron", "", "", "Map tiles by CartoDB, under CC BY 3.0. Data by OpenStreetMap, under ODbL.","http://basemaps.cartocdn.com/light_all/%7Bz%7D/%7Bx%7D/%7By%7D.png", "", "20", "0"])
sources.append(["connections-xyz", "Esri Boundaries Places", "", "", "Requires ArcGIS Onlinesubscription","https://server.arcgisonline.com/ArcGIS/rest/services/Reference/World_Boundaries_and_Places/MapServer/tile/%7Bz%7D/%7By%7D/%7Bx%7D", "", "20", "0"])
sources.append(["connections-xyz", "Esri Gray (dark)", "", "", "Requires ArcGIS Onlinesubscription","http://services.arcgisonline.com/ArcGIS/rest/services/Canvas/World_Dark_Gray_Base/MapServer/tile/%7Bz%7D/%7By%7D/%7Bx%7D", "", "16", "0"])
sources.append(["connections-xyz", "Esri Gray (light)", "", "", "Requires ArcGIS Onlinesubscription","http://services.arcgisonline.com/ArcGIS/rest/services/Canvas/World_Light_Gray_Base/MapServer/tile/%7Bz%7D/%7By%7D/%7Bx%7D", "", "16", "0"])
sources.append(["connections-xyz", "Esri National Geographic", "", "", "Requires ArcGIS Onlinesubscription","http://services.arcgisonline.com/ArcGIS/rest/services/NatGeo_World_Map/MapServer/tile/%7Bz%7D/%7By%7D/%7Bx%7D", "", "12", "0"])
sources.append(["connections-xyz", "Esri Ocean", "", "", "Requires ArcGIS Onlinesubscription","https://services.arcgisonline.com/ArcGIS/rest/services/Ocean/World_Ocean_Base/MapServer/tile/%7Bz%7D/%7By%7D/%7Bx%7D", "", "10", "0"])
sources.append(["connections-xyz", "Esri Satellite", "", "", "Requires ArcGIS Onlinesubscription","https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/%7Bz%7D/%7By%7D/%7Bx%7D", "", "17", "0"])
sources.append(["connections-xyz", "Esri Standard", "", "", "Requires ArcGIS Onlinesubscription","https://server.arcgisonline.com/ArcGIS/rest/services/World_Street_Map/MapServer/tile/%7Bz%7D/%7By%7D/%7Bx%7D", "", "17", "0"])
sources.append(["connections-xyz", "Esri Terrain", "", "", "Requires ArcGIS Onlinesubscription","https://server.arcgisonline.com/ArcGIS/rest/services/World_Terrain_Base/MapServer/tile/%7Bz%7D/%7By%7D/%7Bx%7D", "", "13", "0"])
sources.append(["connections-xyz", "Esri Topo World", "", "", "Requires ArcGIS Onlinesubscription","http://services.arcgisonline.com/ArcGIS/rest/services/World_Topo_Map/MapServer/tile/%7Bz%7D/%7By%7D/%7Bx%7D", "", "20", "0"])
sources.append(["connections-xyz", "Esri Transportation", "", "", "Requires ArcGIS Onlinesubscription","https://server.arcgisonline.com/ArcGIS/rest/services/Reference/World_Transportation/MapServer/tile/%7Bz%7D/%7By%7D/%7Bx%7D", "", "20", "0"])
sources.append(["connections-xyz", "Google Maps", "", "", "","https://mt1.google.com/vt/lyrs=m&x=%7Bx%7D&y=%7By%7D&z=%7Bz%7D", "", "19", "0"])
sources.append(["connections-xyz", "Google Satellite", "", "", "","https://mt1.google.com/vt/lyrs=s&x=%7Bx%7D&y=%7By%7D&z=%7Bz%7D", "", "19", "0"])
sources.append(["connections-xyz", "Google Satellite Hybrid", "", "", "","https://mt1.google.com/vt/lyrs=y&x=%7Bx%7D&y=%7By%7D&z=%7Bz%7D", "", "19", "0"])
sources.append(["connections-xyz", "Google Terrain", "", "", "","https://mt1.google.com/vt/lyrs=t&x=%7Bx%7D&y=%7By%7D&z=%7Bz%7D", "", "19", "0"])
sources.append(["connections-xyz", "Google Terrain Hybrid", "", "", "","https://mt1.google.com/vt/lyrs=p&x=%7Bx%7D&y=%7By%7D&z=%7Bz%7D", "", "19", "0"])
sources.append(["connections-xyz", "Open Weather Map Clouds", "", "", "Map tiles by OpenWeatherMap, under CC BY-SA 4.0","http://tile.openweathermap.org/map/clouds_new/%7Bz%7D/%7Bx%7D/%7By%7D.png?APPID=ef3c5137f6c31db50c4c6f1ce4e7e9dd", "", "19", "0"])
sources.append(["connections-xyz", "Open Weather Map Temperature", "", "", "Map tiles by OpenWeatherMap, under CC BY-SA 4.0","http://tile.openweathermap.org/map/temp_new/%7Bz%7D/%7Bx%7D/%7By%7D.png?APPID=1c3e4ef8e25596946ee1f3846b53218a", "", "19", "0"])
sources.append(["connections-xyz", "Open Weather Map Wind Speed", "", "", "Map tiles by OpenWeatherMap, under CC BY-SA 4.0","http://tile.openweathermap.org/map/wind_new/%7Bz%7D/%7Bx%7D/%7By%7D.png?APPID=f9d0069aa69438d52276ae25c1ee9893", "", "19", "0"])
sources.append(["connections-xyz", "OpenStreetMap", "", "", "","https://tile.openstreetmap.org/{z}/{x}/{y}.png", "", "19", "0"])
sources.append(["connections-xyz", "OpenStreetMap H.O.T.", "", "", "OpenStreetMap contributors, under ODbL","http://tile.openstreetmap.fr/hot/%7Bz%7D/%7Bx%7D/%7By%7D.png", "", "19", "0"])
sources.append(["connections-xyz", "OpenStreetMap Monochrome", "", "", "OpenStreetMap contributors, under ODbL","http://tiles.wmflabs.org/bw-mapnik/%7Bz%7D/%7Bx%7D/%7By%7D.png", "", "19", "0"])
sources.append(["connections-xyz", "OpenStreetMap Standard", "", "", "OpenStreetMap contributors, under ODbL","http://tile.openstreetmap.org/%7Bz%7D/%7Bx%7D/%7By%7D.png", "", "19", "0"])
sources.append(["connections-xyz", "OpenTopoMap", "", "", "Kartendaten: © OpenStreetMap-Mitwirkende, SRTM | Kartendarstellung: © OpenTopoMap (CC-BY-SA)","https://tile.opentopomap.org/%7Bz%7D/%7Bx%7D/%7By%7D.png", "", "17", "1"])
sources.append(["connections-xyz", "Stamen Terrain", "", "", "Map tiles by Stamen Design, under CC BY 3.0. Data by OpenStreetMap, under ODbL","http://tile.stamen.com/terrain/%7Bz%7D/%7Bx%7D/%7By%7D.png", "", "20", "0"])
sources.append(["connections-xyz", "Stamen Toner", "", "", "Map tiles by Stamen Design, under CC BY 3.0. Data by OpenStreetMap, under ODbL","http://tile.stamen.com/toner/%7Bz%7D/%7Bx%7D/%7By%7D.png", "", "20", "0"])
sources.append(["connections-xyz", "Stamen Toner Light", "", "", "Map tiles by Stamen Design, under CC BY 3.0. Data by OpenStreetMap, under ODbL","http://tile.stamen.com/toner-lite/%7Bz%7D/%7Bx%7D/%7By%7D.png", "", "20", "0"])
sources.append(["connections-xyz", "Stamen Watercolor", "", "", "Map tiles by Stamen Design, under CC BY 3.0. Data by OpenStreetMap, under ODbL","http://tile.stamen.com/watercolor/%7Bz%7D/%7Bx%7D/%7By%7D.jpg", "", "18", "0"])
sources.append(["connections-xyz", "Wikimedia Hike Bike Map", "", "", "OpenStreetMap contributors, under ODbL","http://tiles.wmflabs.org/hikebike/%7Bz%7D/%7Bx%7D/%7By%7D.png", "", "17", "1"])

# Add sources to browser
for source in sources:
   connectionType = source[0]
   connectionName = source[1]
   QSettings().setValue("qgis_code/%s/%s/authcfg" % (connectionType, connectionName), source[2])
   QSettings().setValue("qgis_code/%s/%s/password" % (connectionType, connectionName), source[3])
   QSettings().setValue("qgis_code/%s/%s/referer" % (connectionType, connectionName), source[4])
   QSettings().setValue("qgis_code/%s/%s/url" % (connectionType, connectionName), source[5])
   QSettings().setValue("qgis_code/%s/%s/username" % (connectionType, connectionName), source[6])
   QSettings().setValue("qgis_code/%s/%s/zmax" % (connectionType, connectionName), source[7])
   QSettings().setValue("qgis_code/%s/%s/zmin" % (connectionType, connectionName), source[8])

# Update GUI
iface.reloadConnections()

